Laravel 11
blade-ui-kit/blade-icons pull request #223
Opened 2024-01-30 12:33 UTC by robsontenorio

2024-01-30 13:07 UTC, driesvints commented
Heya. Can you also add the new test bench version and update the matrix build on the GHA?

2024-01-30 15:10 UTC, robsontenorio commented
Done!

2024-01-30 15:43 UTC, driesvints requested changes

2024-01-30 15:43 UTC, driesvints commented on composer.json
>          "symfony/finder": "^5.3|^6.0"
You'll have to add Symfony v7 constraints here as well.

2024-01-30 16:14 UTC, robsontenorio commented on composer.json
>          "symfony/finder": "^5.3|^6.0"
<img width="864" alt="image" src="https://github.com/blade-ui-kit/blade-icons/assets/118955/66cb858a-3ce4-4687-ab2c-3405300f65c2">

2024-01-31 08:03 UTC, driesvints commented
What's weird is that the exact same build on Ubuntu does work. I'm gonna leave this open until after Laravel v11's release and then merge and tag.

2024-02-07 16:08 UTC, merged

2024-02-07 16:09 UTC, driesvints commented
Is disabled the Laravel v11 windows build for now. Thanks!

2024-02-07 16:37 UTC, owenvoke commented
This might be happening because Windows treats `^` as an escape character. 🤔 If this is the issue, an alternative is to change to `"illuminate/contracts=${{ matrix.laravel }}.*"` 🙂

2024-02-07 16:44 UTC, driesvints commented
@owenvoke seems that worked! https://github.com/blade-ui-kit/blade-icons/pull/224

Thanks :)