Accessible SVG icons: Add title tag inside SVG if the title attribute is set
blade-ui-kit/blade-icons pull request #245
Opened 2024-07-26 03:30 UTC by aarishgilani

Heya!  👋🏼 First time contributor here!

Considering WCAG accessibility compliance, semantic icons require alternate text. Ref: [FontAwesome Documentation](https://docs.fontawesome.com/web/dig-deeper/accessibility).

We could add a `<title>` tag under SVG element and an aria-labelledby attribute to meet compliance requirements. See pattern 8 on [Deque Best Practices](https://www.deque.com/blog/creating-accessible-svgs/).

For example, 

**This component:**
```html
<x-icon-solid.camera title="camera" />
```

**Could result in the following markup:**
```html
<svg class="svg-inline--fa fa-arrow-right" aria-labelledby="svg-inline--title-ajx18rtJBjSu" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">

<title id="svg-inline--title-ajx18rtJBjSu">camera</title>

<path fill="currentColor" d="M438.6 278.6c12.5-12.5 12.5-32.8 0-45.3l-160-160c-12.5-12.5-32.8-12.5-45.3 0s-12.5 32.8 0 45.3L338.8 224 32 224c-17.7 0-32 14.3-32 32s14.3 32 32 32l306.7 0L233.4 393.4c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0l160-160z"></path>

</svg>
```
 
I am trying to incorporate this package in our agencie's workflow but cannot get accessibility team to sign off until we have a way to make this compliant. I am open to suggestions and looking forward to contribute!

2024-07-26 07:42 UTC, driesvints commented on src/Svg.php
> +        $this->attributes['aria-labelledby'] = $title_id;
```suggestion
        $titleId = 'svg-inline--title-'.Str::random(10);

        // create title element
        $title = '<title id='.$titleId.'>'.$this->attributes['title'].'</title>';

        // add aria-labelledby attribute to svg element
        $this->attributes['aria-labelledby'] = $titleId;
```

2024-07-26 07:44 UTC, driesvints requested changes
This is great @aarishgilani. Can you also add a test and add a section to docs about this?

2024-07-26 07:44 UTC, driesvints commented on src/Svg.php
> +            $this->contents = $this->addTitle();
One thing I'd change here is pass the title directly to the method as a param.

```suggestion
            $this->contents = $this->addTitle($this->attributes['title']);
```

2024-07-26 19:44 UTC, aarishgilani commented
@driesvints Thanks for quick response, I have made the suggested updates and also wrote some tests. @jdmghost, Accessibility expert on our team also helped with the documentation.

Let me know if it needs any updates!

2024-07-29 07:17 UTC, driesvints requested changes
Thanks @aarishgilani. Just one last remark and then this is ready to merge. I appreciate the effort here!

2024-07-29 07:17 UTC, driesvints commented on README.md
> +- `aria-labelledby` to refer to the unique ID of the title element
Maybe just add one practical code example on how to use this?

2024-07-29 21:49 UTC, merged

2024-07-29 21:49 UTC, driesvints commented
Thanks!