Register optimize commands
blade-ui-kit/blade-icons pull request #253
Opened 2024-10-09 09:36 UTC by erikgaal

[Newly introduced in Laravel 11.27](https://github.com/laravel/framework/pull/52928), packages can now register the commands that should run during the `optimize` phase of deployment.

This PR adds the recommended steps for optimizing whenever it's available.

2024-10-10 07:43 UTC, driesvints requested changes
Thanks! Just one remark.

2024-10-10 07:43 UTC, driesvints commented on src/BladeIconsServiceProvider.php
> +                );
Can we not use named arguments so we don't have to drop older PHP versions?

2024-10-17 09:26 UTC, erikgaal reviewed
don't use named arguments

2024-10-17 17:38 UTC, merged

2024-10-17 17:38 UTC, driesvints commented
Thanks!